services:
  opensearch:
    image: opensearchproject/opensearch:3.5.0
    container_name: wurth-opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Admin@1234!
      - DISABLE_SECURITY_PLUGIN=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - plugins.ml_commons.only_run_on_ml_node=false
      - plugins.ml_commons.allow_registering_model_via_url=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - wurth-net
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 15s
      timeout: 10s
      retries: 12
      start_period: 30s

  api:
    build:
      context: ..
      dockerfile: services/api/Dockerfile
    container_name: wurth-api
    ports:
      - "8000:8000"
    depends_on:
      opensearch:
        condition: service_healthy
    env_file:
      - ../.env.docker
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_USE_SSL=false
      - OPENSEARCH_VERIFY_CERTS=false
      - INDEX_NAME=products
      - EMBEDDING_MODEL=BAAI/bge-small-en-v1.5
      - LOG_LEVEL=INFO
    networks:
      - wurth-net
    restart: unless-stopped
    volumes:
      - hf-model-cache:/root/.cache/huggingface

  ingestion:
    build:
      context: ..
      dockerfile: services/ingestion/Dockerfile
    container_name: wurth-ingestion
    depends_on:
      opensearch:
        condition: service_healthy
    env_file:
      - ../.env.docker
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_USE_SSL=false
      - OPENSEARCH_VERIFY_CERTS=false
      - INDEX_NAME=products
      - EMBEDDING_MODEL=BAAI/bge-small-en-v1.5
      - BATCH_SIZE=128
      - CHUNK_SIZE=500
      - HF_DATASET=McAuley-Lab/Amazon-Reviews-2023
      - HF_DATASET_CONFIG=raw_meta_All_Beauty
    profiles:
      - ingest
    networks:
      - wurth-net
    volumes:
      - hf-model-cache:/root/.cache/huggingface
      - hf-dataset-cache:/root/.cache/huggingface/datasets

volumes:
  opensearch-data:
    driver: local
  hf-model-cache:
    driver: local
  hf-dataset-cache:
    driver: local

networks:
  wurth-net:
    driver: bridge